# Identical to main testing workflow, but points only
# at dev branch
name: Testing[master]
on:
  push:
    branches: [ main ]
jobs:
  # Build the Hello World test application
  build-hello_world:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        love_version: ['11.4', '11.3', '11.2', '0.10.2', '0.9.2', '0.8.0']
    steps:
    - uses: actions/checkout@v3
    - uses: nhartland/love-build@master
      id: love-build
      with:
        app_name: 'Ecopolia'
        love_version: ${{ matrix.love_version }}
    # Upload the resulting artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: hw_macos-build
        path: ${{ steps.love-build.outputs.macos-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: hw_win32-build
        path: ${{ steps.love-build.outputs.win32-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: hw_win64-build
        path: ${{ steps.love-build.outputs.win64-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: hw_love-build
        path: ${{ steps.love-build.outputs.love-filename }}
