# Build all and Create Release
on:
  push:
    branches: [main]

jobs:
  # Build the Hello World test application
  build-ecopolia:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        love_version: ['11.4']
    
    steps:
      - uses: actions/checkout@v3
      - uses: nhartland/love-build@master
        id: love-build
        with:
          app_name: 'Ecopolia'
          love_version: ${{ matrix.love_version }}
    
      # Upload the resulting artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: ecopolia_macos-build
          path: ${{ steps.love-build.outputs.macos-filename }}
        id: upload_macos
    
      - uses: actions/upload-artifact@v1
        with:
          name: ecopolia_win32-build
          path: ${{ steps.love-build.outputs.win32-filename }}
        id: upload_win32
    
      - uses: actions/upload-artifact@v1
        with:
          name: ecopolia_win64-build
          path: ${{ steps.love-build.outputs.win64-filename }}
        id: upload_win64
    
      - uses: actions/upload-artifact@v1
        with:
          name: ecopolia_love-build
          path: ${{ steps.love-build.outputs.love-filename }}
        id: upload_love

  # Create a release
  create-release:
    needs: build-ecopolia
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Download the built artifacts
      - name: Download macOS build
        uses: actions/download-artifact@v1
        with:
          name: ecopolia_macos-build
          path: ecopolia_builds/macos
        
      - name: Download Win32 build
        uses: actions/download-artifact@v1
        with:
          name: ecopolia_win32-build
          path: ecopolia_builds/win32
        
      - name: Download Win64 build
        uses: actions/download-artifact@v1
        with:
          name: ecopolia_win64-build
          path: ecopolia_builds/win64
        
      - name: Download Love build
        uses: actions/download-artifact@v1
        with:
          name: ecopolia_love-build
          path: ecopolia_builds/love

      # Create a release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Specify the tag name for the release
          release_name: Release v1.0.0  # Specify the name of the release
          body: |
            This is the release description.
            You can provide more information about the release here.
          draft: false
          prerelease: false
      
      # Upload the built artifacts as release assets
      - name: Upload macOS build as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ecopolia_builds/macos
          asset_name: ecopolia-macos.zip
          asset_content_type: application/zip
        
      - name: Upload Win32 build as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ecopolia_builds/win32
          asset_name: ecopolia-win32.zip
          asset_content_type: application/zip
        
      - name: Upload Win64 build as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ecopolia_builds/win64
          asset_name: ecopolia-win64.zip
          asset_content_type: application/zip
        
      - name: Upload Love build as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ecopolia_builds/love
          asset_name: ecopolia.love
          asset_content_type: application/octet-stream
