# Build all and Create Release
on:
  push:
    branches: [main]

jobs:
  # Build the Hello World test application
  build-ecopolia:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        love_version: ['11.4']
    
    steps:
      - uses: actions/checkout@v3
      - uses: nhartland/love-build@master
        id: love-build
        with:
          app_name: 'Ecopolia'
          love_version: ${{ matrix.love_version }}
    
      # Upload the resulting artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: ecopolia_macos-build
          path: ${{ steps.love-build.outputs.macos-filename }}
        id: upload_macos
    
      - uses: actions/upload-artifact@v1
        with:
          name: ecopolia_win32-build
          path: ${{ steps.love-build.outputs.win32-filename }}
        id: upload_win32
    
      - uses: actions/upload-artifact@v1
        with:
          name: ecopolia_win64-build
          path: ${{ steps.love-build.outputs.win64-filename }}
        id: upload_win64
    
      - uses: actions/upload-artifact@v1
        with:
          name: ecopolia_love-build
          path: ${{ steps.love-build.outputs.love-filename }}
        id: upload_love

  # Create a release with the built artifacts
  create-release:
    needs: build-ecopolia
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Release created by GitHub Actions
          draft: false
          prerelease: false
      
      # Attach the built artifacts to the release
      - name: Attach Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ecopolia-artifacts
          path: |
            ${{ needs.build-ecopolia.outputs.macos-filename }}
            ${{ needs.build-ecopolia.outputs.win32-filename }}
            ${{ needs.build-ecopolia.outputs.win64-filename }}
            ${{ needs.build-ecopolia.outputs.love-filename }}
